[package]
name = "sambar"
version = "0.0.1"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
tempfile = "3.19.1"
wayland-client = "0.31.7"
wayland-protocols = { version = "0.32.5", features = ["client"] }
